### ISSUE TITLE
Burp Suite extension loading error

### ISSUE THREAD

**Issue by sangamthakur-sec** [SySS-Research/burp-extender-json-api#3]
Hi 

Bdw great extension

I was loading up the extension into burp pro via burp extension >> add>>Selecting the file downloaded from "burp extension/release/jar-name.jar" but it throws the error

java.lang.UnsupportedOperationException: No class provided, and an appropriate one cannot be found.
	at org.apache.logging.log4j.LogManager.callerClass(LogManager.java:555)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:580)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:567)
	at burp.BurpExtender.<clinit>(BurpExtender.java:30)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:427)
	at burp.eux.a(Unknown Source)
	at burp.eux.<init>(Unknown Source)
	at burp.pe.a(Unknown Source)
	at burp.cc_.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

Also can you please state one use case "How we can access the extension outside burp or using cli"

**Comment by happyc0ding** [comment]
I have changed some dependencies and created a new release. It worked for me with a current burp version. I have not run detailed tests though, I will probably do some more development next year.

Please re-open this issue if your problem persists.
